---
- name: Query MAC Address Table from Juniper Switches
  hosts: juniper_switches
  gather_facts: no
  vars:
    target_mac: "{{ mac_address | upper }}"
    
  tasks:
    - name: Get MAC address table
      ansible.netcommon.cli_command:
        command: "show ethernet-switching table"
      register: mac_table_result
      
    - name: Filter MAC results
      set_fact:
        filtered_output: "{{ mac_table_result.stdout | regex_findall('.*' + target_mac + '.*') }}"
      
    - name: Display results
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          MAC Address: {{ target_mac }}
          {% if filtered_output %}
          Found entries:
          {% for entry in filtered_output %}
          {{ entry }}
          {% endfor %}
          {% else %}
          No matching MAC address found
          {% endif %}
